# Generated by Django 4.2.4 on 2023-09-14 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=250)),
                ('tipoAsesor', models.CharField(choices=[('tecnico', 'Tecnico'), ('academico', 'Academico')], max_length=50)),
                ('idEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
        ),
    ]
