# Generated by Django 4.2.4 on 2023-09-14 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrutinioSeguridad', models.BooleanField(blank=True, default=False, null=True)),
                ('reporteDiseno', models.IntegerField(blank=True, null=True)),
                ('rubricaPresentaciones', models.IntegerField(blank=True, null=True)),
                ('aceleracionFrenado', models.IntegerField(blank=True, null=True)),
                ('rubricaManiobrabilidad', models.IntegerField(blank=True, null=True)),
                ('hillTraction', models.IntegerField(blank=True, null=True)),
                ('rubricaResistencia', models.IntegerField(blank=True, null=True)),
                ('circuitoPrimeraVez', models.CharField(blank=True, max_length=50, null=True)),
                ('circuitoSegundaVez', models.CharField(blank=True, max_length=50, null=True)),
                ('aceleracionPrimeraVez', models.CharField(blank=True, max_length=50, null=True)),
                ('aceleracionSegundaVez', models.CharField(blank=True, max_length=50, null=True)),
                ('idEquipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='equipo.equipo')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
