# Generated by Django 4.2.4 on 2023-09-08 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubrica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipoPrueba', models.CharField(choices=[('check', 'Check'), ('manual', 'Manual')], default='manual', max_length=250)),
                ('puntaje', models.IntegerField(blank=True, default=0, null=True)),
                ('idRubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrica.rubrica')),
            ],
        ),
    ]
