# Generated by Django 4.2.4 on 2023-09-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_alter_prueba_aceleracionfrenado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='aceleracionFrenadoCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='hillTractionCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='reporteDisenoCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='rubricaManiobrabilidadCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='rubricaPresentacionesCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='rubricaResistenciaCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
