# Generated by Django 4.2.4 on 2023-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_prueba_aceleracionfrenadocalificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='aceleracionCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='circuitoCalificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
