# Generated by Django 4.2.4 on 2023-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0007_prueba_aceleracioncalificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='aceleracionFrenado',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='aceleracionPrimeraVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='aceleracionSegundaVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='circuitoPrimeraVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='circuitoSegundaVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hillTraction',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='reporteDiseno',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='rubricaManiobrabilidad',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='rubricaPresentaciones',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='rubricaResistencia',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
    ]
