# Generated by Django 4.2.4 on 2023-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0008_alter_prueba_aceleracionfrenado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='hillTraction',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='reporteDiseno',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='reporteDisenoCalificado',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='rubricaManiobrabilidad',
        ),
        migrations.AddField(
            model_name='prueba',
            name='hillTractionPrimeraVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='hillTractionSegundaVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='maniobrabilidadPrimeraVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='maniobrabilidadSegundaVez',
            field=models.CharField(blank=True, default='0.0', max_length=50, null=True),
        ),
    ]
