# Generated by Django 4.2.4 on 2023-09-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntaje',
            old_name='mayorTiempoAceleracion',
            new_name='menorTiempoAceleracion',
        ),
        migrations.RenameField(
            model_name='puntaje',
            old_name='mayorTiempoCircuito',
            new_name='menorTiempoCircuito',
        ),
    ]
