# Generated by Django 4.2.4 on 2023-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntaje', '0002_rename_mayortiempoaceleracion_puntaje_menortiempoaceleracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='totalPuntaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
