# Generated by Django 4.2.4 on 2023-09-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('encargado', 'Encargado'), ('juez', 'Juez')], default='admin', max_length=9),
        ),
    ]
